<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationTitle>Geistes Funke</ApplicationTitle>
    <AssemblyName>GeistesFunke</AssemblyName>
    <Product>Geistes Funke</Product>
    <AssemblyTitle>Geistes Funke</AssemblyTitle>
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Fonts\*.ttf" />
    <Resource Include="Assets\icon.ico" />
    <Resource Include="Assets\logo-light.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SparkVault.Core\SparkVault.Core.csproj" />
  </ItemGroup>

</Project>
